---
title: "Hello World"
description: "\\> whoami"
---

Hi! My name is Harry Fisher, thanks for visiting my site. I currently work as a Senior R Engineer at [Seven Bridges](https://www.sevenbridges.com/), developing and maintaining a range of R packages and shiny applications. Previously, I have worked as a data scientist in the pharmaceutical, and financial crime & compliance sectors. I am very enthusiastic about the R programming language, and enjoy trying to solve challenging problems and learning new tricks. I have also recently become a RStudio [certified instructor](https://education.rstudio.com/trainers/people/fisher+harry/) for working with the tidyverse. I occasionally write about things I'm working and hopefully share interesting things on my blog. Feel free to get in touch if any of the posts catch your interest!

### Research

In a different life, I completed my [Ph.D.](https://github.com/hfshr/phd-thesis/blob/master/full_phd.pdf) at Cardiff Metropolitan University where I investigated risk factors associated with sports injury from an interdisciplinary perspective. Below are some research articles that I published along the way.

* Fisher et al. 2020. An interdisciplinary examination of stress and injury in athletes. [[Link]](https://www.frontiersin.org/articles/10.3389/fspor.2020.595619/abstract)
  
* Fisher et al. 2016. Relationship between Force Production during Isometric Squats and Knee Flexion Angles during Landing. Journal of Strength and Conditioning. [[pdf]](data/pdfs/fisher-2016.pdf)

### Contact

<div class="mylinks">
<p style="text-align: center;">
    <a href="https://github.com/hfshr" target="_blank" class="fa fa-github"  style="font-size:36px;"></a>
    <a href="mailto:harryfisher21@gmail.com" target="_blank" class="fa fa-envelope" style="font-size:36px;"></a>
    <a href="https://www.linkedin.com/in/drharryfisher/" target="_blank" class="fa fa-linkedin-square" style="font-size:36px;"></a>
    <a href="https://twitter.com/harryfishr" target="_blank" class="fa fa-twitter" style="font-size:36px;"></a>
</p>
</div>


